### ISSUE TITLE
How does LSP support matter for a colorscheme?

### ISSUE THREAD

**Issue by will** [shaunsingh/solarized.nvim#4]
I haven't kept up to date with the soon-to-be but yet unreleased neovim features, but just started looking today, and found this project. I can see how a colorscheme could take advantage of tree-sitter, but in your readme you also call out the "built-in LSP" neovim feature.

I'm just curious, but can you tell me how that has anything to do with a colorscheme?

**Comment by shaunsingh** [comment]
Sorry for the delay 

The colorscheme adds highlight groups that the lsp (and other lsp plugins e.g. lsp saga), use for error and warning highlighting, as well as code popups (lspsaga) and signatures (lsp-signature).
